name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flashapp:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Pull and Run Docker Container on EC2
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/flashapp:latest
          docker stop myappcontainer || true
          docker rm myappcontainer || true
          docker run -d --name myappcontainer -p 5000:5000 ${{ secrets.DOCKER_HUB_USERNAME }}/flashapp:latest
